set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/dworpell/UART_Tester/UART_Tester.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc rfile:../../../UART_Tester.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/clk_wiz_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/afs/ece.cmu.edu/usr/dworpell/UART_Tester/UART_Tester.srcs/constrs_1/new/constrats.xdc rfile:../../../UART_Tester.srcs/constrs_1/new/constrats.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1_p]] 0.05
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports {LED[0]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN39 [get_ports {LED[1]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR37 [get_ports {LED[2]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT37 [get_ports {LED[3]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR35 [get_ports {LED[4]}]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP41 [get_ports {LED[5]}]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP42 [get_ports {LED[6]}]
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU39 [get_ports {LED[7]}]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV40 [get_ports CPU_RESET]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_RESET]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP40 [get_ports GPIO_SW_S]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR40 [get_ports GPIO_SW_N]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV39 [get_ports GPIO_SW_C]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_C]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU38 [get_ports GPIO_SW_E]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW40 [get_ports GPIO_SW_W]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports GPIO_SW_W]
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports SYSCLK_P]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports SYSCLK_N]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU36 [get_ports TX]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU33 [get_ports RX]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT32 [get_ports RTS]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR34 [get_ports CTS]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/clk_wiz_0/inst/clk_out1]]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 13 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[1]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[2]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[3]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[4]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[5]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[6]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[7]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[8]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[9]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[10]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[11]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[12]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/BIT_COUNTER/count_reg[13]}]]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {LED_OBUF[0]} {LED_OBUF[1]} {LED_OBUF[2]} {LED_OBUF[3]} {LED_OBUF[4]} {LED_OBUF[5]} {LED_OBUF[6]} {LED_OBUF[7]}]]
set_property src_info {type:XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[0]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[1]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[2]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[3]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[4]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[5]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[6]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[7]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[8]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[9]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[10]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[11]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[12]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/SAMPLE_CLK_COUNTER/clk_counter[13]}]]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[0]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[1]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[2]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[3]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[4]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[5]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[6]} {design_1_i/ControlModuleWrapper_0/inst/nolabel_line31/sreg0[7]}]]
set_property src_info {type:XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_i/RX]]
set_property src_info {type:XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out1]
