# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/ece.cmu.edu/usr/dworpell/project_11/project_11.srcs/constrs_1/new/cosntrats.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2}]

# IP: bd/design_2/ip/design_2_clk_wiz_0_0/design_2_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_clk_wiz_0_0 || ORIG_REF_NAME==design_2_clk_wiz_0_0}]

# IP: bd/design_2/ip/design_2_xlconstant_0_0/design_2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconstant_0_0 || ORIG_REF_NAME==design_2_xlconstant_0_0}]

# IP: bd/design_2/ip/design_2_xlconcat_0_1/design_2_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_0_1 || ORIG_REF_NAME==design_2_xlconcat_0_1}]

# IP: bd/design_2/ip/design_2_WaitForInput_0_1/design_2_WaitForInput_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_WaitForInput_0_1 || ORIG_REF_NAME==design_2_WaitForInput_0_1}]

# IP: bd/design_2/ip/design_2_xlslice_0_0/design_2_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlslice_0_0 || ORIG_REF_NAME==design_2_xlslice_0_0}]

# IP: bd/design_2/ip/design_2_xlconcat_1_0/design_2_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xlconcat_1_0 || ORIG_REF_NAME==design_2_xlconcat_1_0}]

# XDC: bd/design_2/design_2_ooc.xdc
