# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /afs/ece.cmu.edu/usr/dworpell/project_11/project_11.srcs/constrs_1/new/cosntrats.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0}]

# IP: bd/design_1/ip/design_1_BLSControllerWrapper_0_0/design_1_BLSControllerWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BLSControllerWrapper_0_0 || ORIG_REF_NAME==design_1_BLSControllerWrapper_0_0}]

# IP: bd/design_1/ip/design_1_PacketRegisterWrapper_0_0/design_1_PacketRegisterWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PacketRegisterWrapper_0_0 || ORIG_REF_NAME==design_1_PacketRegisterWrapper_0_0}]

# IP: bd/design_1/ip/design_1_DataManagerWrapper_0_0/design_1_DataManagerWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_DataManagerWrapper_0_0 || ORIG_REF_NAME==design_1_DataManagerWrapper_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_BlkSchlsEqEuroNoDiv_0_0/design_1_BlkSchlsEqEuroNoDiv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BlkSchlsEqEuroNoDiv_0_0 || ORIG_REF_NAME==design_1_BlkSchlsEqEuroNoDiv_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_1/design_1_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_1 || ORIG_REF_NAME==design_1_blk_mem_gen_0_1}]

# IP: bd/design_1/ip/design_1_ControlModuleWrapper_0_0/design_1_ControlModuleWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_ControlModuleWrapper_0_0 || ORIG_REF_NAME==design_1_ControlModuleWrapper_0_0}]

# IP: bd/design_1/ip/design_1_UARTTOMEMWrapper_0_0/design_1_UARTTOMEMWrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_UARTTOMEMWrapper_0_0 || ORIG_REF_NAME==design_1_UARTTOMEMWrapper_0_0}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_1_0/design_1_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_1_0 || ORIG_REF_NAME==design_1_blk_mem_gen_1_0}]

# IP: bd/design_1/ip/design_1_Mux2to1Wrapper_0_3/design_1_Mux2to1Wrapper_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Mux2to1Wrapper_0_3 || ORIG_REF_NAME==design_1_Mux2to1Wrapper_0_3}]

# XDC: bd/design_1/design_1_ooc.xdc
