-- Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2017.2 (lin64) Build 1909853 Thu Jun 15 18:39:10 MDT 2017
-- Date        : Wed Oct 24 11:13:49 2018
-- Host        : liberty.andrew.cmu.edu running 64-bit Red Hat Enterprise Linux Server release 7.5 (Maipo)
-- Command     : write_vhdl -force -mode funcsim
--               /afs/ece.cmu.edu/usr/dworpell/project_12/project_12.srcs/sources_1/bd/design_1/ip/design_1_Constants_0_0/design_1_Constants_0_0_sim_netlist.vhdl
-- Design      : design_1_Constants_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7vx485tffg1761-2
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity design_1_Constants_0_0 is
  port (
    sptprice : out STD_LOGIC_VECTOR ( 31 downto 0 );
    strike : out STD_LOGIC_VECTOR ( 31 downto 0 );
    rate : out STD_LOGIC_VECTOR ( 31 downto 0 );
    volatility : out STD_LOGIC_VECTOR ( 31 downto 0 );
    time_r : out STD_LOGIC_VECTOR ( 31 downto 0 );
    otype : out STD_LOGIC_VECTOR ( 31 downto 0 );
    timet : out STD_LOGIC_VECTOR ( 31 downto 0 )
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of design_1_Constants_0_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of design_1_Constants_0_0 : entity is "design_1_Constants_0_0,Constants,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of design_1_Constants_0_0 : entity is "yes";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of design_1_Constants_0_0 : entity is "Constants,Vivado 2017.2";
end design_1_Constants_0_0;

architecture STRUCTURE of design_1_Constants_0_0 is
  signal \<const0>\ : STD_LOGIC;
  signal \<const1>\ : STD_LOGIC;
begin
  otype(31) <= \<const0>\;
  otype(30) <= \<const0>\;
  otype(29) <= \<const1>\;
  otype(28) <= \<const1>\;
  otype(27) <= \<const1>\;
  otype(26) <= \<const1>\;
  otype(25) <= \<const1>\;
  otype(24) <= \<const1>\;
  otype(23) <= \<const1>\;
  otype(22) <= \<const0>\;
  otype(21) <= \<const0>\;
  otype(20) <= \<const0>\;
  otype(19) <= \<const0>\;
  otype(18) <= \<const0>\;
  otype(17) <= \<const0>\;
  otype(16) <= \<const0>\;
  otype(15) <= \<const0>\;
  otype(14) <= \<const0>\;
  otype(13) <= \<const0>\;
  otype(12) <= \<const0>\;
  otype(11) <= \<const0>\;
  otype(10) <= \<const0>\;
  otype(9) <= \<const0>\;
  otype(8) <= \<const0>\;
  otype(7) <= \<const0>\;
  otype(6) <= \<const0>\;
  otype(5) <= \<const0>\;
  otype(4) <= \<const0>\;
  otype(3) <= \<const0>\;
  otype(2) <= \<const0>\;
  otype(1) <= \<const0>\;
  otype(0) <= \<const0>\;
  rate(31) <= \<const0>\;
  rate(30) <= \<const1>\;
  rate(29) <= \<const0>\;
  rate(28) <= \<const0>\;
  rate(27) <= \<const0>\;
  rate(26) <= \<const0>\;
  rate(25) <= \<const0>\;
  rate(24) <= \<const0>\;
  rate(23) <= \<const0>\;
  rate(22) <= \<const0>\;
  rate(21) <= \<const0>\;
  rate(20) <= \<const0>\;
  rate(19) <= \<const0>\;
  rate(18) <= \<const0>\;
  rate(17) <= \<const0>\;
  rate(16) <= \<const0>\;
  rate(15) <= \<const0>\;
  rate(14) <= \<const0>\;
  rate(13) <= \<const0>\;
  rate(12) <= \<const0>\;
  rate(11) <= \<const0>\;
  rate(10) <= \<const0>\;
  rate(9) <= \<const0>\;
  rate(8) <= \<const0>\;
  rate(7) <= \<const0>\;
  rate(6) <= \<const0>\;
  rate(5) <= \<const0>\;
  rate(4) <= \<const0>\;
  rate(3) <= \<const0>\;
  rate(2) <= \<const0>\;
  rate(1) <= \<const0>\;
  rate(0) <= \<const0>\;
  sptprice(31) <= \<const0>\;
  sptprice(30) <= \<const0>\;
  sptprice(29) <= \<const1>\;
  sptprice(28) <= \<const1>\;
  sptprice(27) <= \<const1>\;
  sptprice(26) <= \<const1>\;
  sptprice(25) <= \<const1>\;
  sptprice(24) <= \<const1>\;
  sptprice(23) <= \<const1>\;
  sptprice(22) <= \<const0>\;
  sptprice(21) <= \<const0>\;
  sptprice(20) <= \<const0>\;
  sptprice(19) <= \<const0>\;
  sptprice(18) <= \<const0>\;
  sptprice(17) <= \<const0>\;
  sptprice(16) <= \<const0>\;
  sptprice(15) <= \<const0>\;
  sptprice(14) <= \<const0>\;
  sptprice(13) <= \<const0>\;
  sptprice(12) <= \<const0>\;
  sptprice(11) <= \<const0>\;
  sptprice(10) <= \<const0>\;
  sptprice(9) <= \<const0>\;
  sptprice(8) <= \<const0>\;
  sptprice(7) <= \<const0>\;
  sptprice(6) <= \<const0>\;
  sptprice(5) <= \<const0>\;
  sptprice(4) <= \<const0>\;
  sptprice(3) <= \<const0>\;
  sptprice(2) <= \<const0>\;
  sptprice(1) <= \<const0>\;
  sptprice(0) <= \<const0>\;
  strike(31) <= \<const0>\;
  strike(30) <= \<const0>\;
  strike(29) <= \<const1>\;
  strike(28) <= \<const1>\;
  strike(27) <= \<const1>\;
  strike(26) <= \<const1>\;
  strike(25) <= \<const1>\;
  strike(24) <= \<const1>\;
  strike(23) <= \<const1>\;
  strike(22) <= \<const0>\;
  strike(21) <= \<const0>\;
  strike(20) <= \<const0>\;
  strike(19) <= \<const1>\;
  strike(18) <= \<const1>\;
  strike(17) <= \<const0>\;
  strike(16) <= \<const0>\;
  strike(15) <= \<const1>\;
  strike(14) <= \<const1>\;
  strike(13) <= \<const0>\;
  strike(12) <= \<const0>\;
  strike(11) <= \<const1>\;
  strike(10) <= \<const1>\;
  strike(9) <= \<const0>\;
  strike(8) <= \<const0>\;
  strike(7) <= \<const1>\;
  strike(6) <= \<const1>\;
  strike(5) <= \<const0>\;
  strike(4) <= \<const0>\;
  strike(3) <= \<const1>\;
  strike(2) <= \<const1>\;
  strike(1) <= \<const0>\;
  strike(0) <= \<const1>\;
  time_r(31) <= \<const0>\;
  time_r(30) <= \<const1>\;
  time_r(29) <= \<const0>\;
  time_r(28) <= \<const0>\;
  time_r(27) <= \<const0>\;
  time_r(26) <= \<const0>\;
  time_r(25) <= \<const0>\;
  time_r(24) <= \<const0>\;
  time_r(23) <= \<const0>\;
  time_r(22) <= \<const0>\;
  time_r(21) <= \<const0>\;
  time_r(20) <= \<const0>\;
  time_r(19) <= \<const0>\;
  time_r(18) <= \<const0>\;
  time_r(17) <= \<const0>\;
  time_r(16) <= \<const0>\;
  time_r(15) <= \<const0>\;
  time_r(14) <= \<const0>\;
  time_r(13) <= \<const0>\;
  time_r(12) <= \<const0>\;
  time_r(11) <= \<const0>\;
  time_r(10) <= \<const0>\;
  time_r(9) <= \<const0>\;
  time_r(8) <= \<const0>\;
  time_r(7) <= \<const0>\;
  time_r(6) <= \<const0>\;
  time_r(5) <= \<const0>\;
  time_r(4) <= \<const0>\;
  time_r(3) <= \<const0>\;
  time_r(2) <= \<const0>\;
  time_r(1) <= \<const0>\;
  time_r(0) <= \<const0>\;
  timet(31) <= \<const0>\;
  timet(30) <= \<const0>\;
  timet(29) <= \<const1>\;
  timet(28) <= \<const1>\;
  timet(27) <= \<const1>\;
  timet(26) <= \<const1>\;
  timet(25) <= \<const1>\;
  timet(24) <= \<const0>\;
  timet(23) <= \<const0>\;
  timet(22) <= \<const1>\;
  timet(21) <= \<const0>\;
  timet(20) <= \<const0>\;
  timet(19) <= \<const1>\;
  timet(18) <= \<const1>\;
  timet(17) <= \<const0>\;
  timet(16) <= \<const0>\;
  timet(15) <= \<const1>\;
  timet(14) <= \<const1>\;
  timet(13) <= \<const0>\;
  timet(12) <= \<const0>\;
  timet(11) <= \<const1>\;
  timet(10) <= \<const1>\;
  timet(9) <= \<const0>\;
  timet(8) <= \<const0>\;
  timet(7) <= \<const1>\;
  timet(6) <= \<const1>\;
  timet(5) <= \<const0>\;
  timet(4) <= \<const0>\;
  timet(3) <= \<const1>\;
  timet(2) <= \<const1>\;
  timet(1) <= \<const0>\;
  timet(0) <= \<const1>\;
  volatility(31) <= \<const0>\;
  volatility(30) <= \<const1>\;
  volatility(29) <= \<const0>\;
  volatility(28) <= \<const0>\;
  volatility(27) <= \<const0>\;
  volatility(26) <= \<const0>\;
  volatility(25) <= \<const0>\;
  volatility(24) <= \<const0>\;
  volatility(23) <= \<const0>\;
  volatility(22) <= \<const1>\;
  volatility(21) <= \<const0>\;
  volatility(20) <= \<const0>\;
  volatility(19) <= \<const0>\;
  volatility(18) <= \<const0>\;
  volatility(17) <= \<const0>\;
  volatility(16) <= \<const0>\;
  volatility(15) <= \<const0>\;
  volatility(14) <= \<const0>\;
  volatility(13) <= \<const0>\;
  volatility(12) <= \<const0>\;
  volatility(11) <= \<const0>\;
  volatility(10) <= \<const0>\;
  volatility(9) <= \<const0>\;
  volatility(8) <= \<const0>\;
  volatility(7) <= \<const0>\;
  volatility(6) <= \<const0>\;
  volatility(5) <= \<const0>\;
  volatility(4) <= \<const0>\;
  volatility(3) <= \<const0>\;
  volatility(2) <= \<const0>\;
  volatility(1) <= \<const0>\;
  volatility(0) <= \<const0>\;
GND: unisim.vcomponents.GND
     port map (
      G => \<const0>\
    );
VCC: unisim.vcomponents.VCC
     port map (
      P => \<const1>\
    );
end STRUCTURE;
