##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  Tue Nov 6 01:00:14 2018
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       VIRTEX7
##                    FPGA Part:         XC7VX690TFFG1761_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M8XX-125
## Data Width: 64
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 2.5 [get_ports sys_clk_p]
          
#create_clock -period 5 [get_ports clk_ref_i]
          
############## NET - IOSTANDARD ##################


